global using System.ComponentModel;
global using System.Diagnostics;
global using System.Numerics;
global using System.Runtime.InteropServices;
global using System.Text.Json.Serialization;
global using Arch.Core;
global using HelixToolkit.Nex.Graphics;
global using HelixToolkit.Nex.Maths;
global using Microsoft.Extensions.Logging;
global using Matrix = System.Numerics.Matrix4x4;
global using Vertex = System.Numerics.Vector4;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;
