using HelixToolkit.Nex.Graphics;

namespace HelixToolkit.Nex.Repository;

/// <summary>
/// Interface for a thread-safe repository that caches sampler state resources.
/// </summary>
/// <remarks>
/// This interface provides access to sampler caching functionality, enabling:
/// <list type="bullet">
/// <item><description>Automatic deduplication of sampler resources</description></item>
/// <item><description>LRU eviction policy for memory management</description></item>
/// <item><description>Cache statistics and monitoring</description></item>
/// <item><description>Thread-safe concurrent access</description></item>
/// </list>
/// </remarks>
public interface ISamplerRepository : IDisposable
{
    /// <summary>
    /// Gets the number of cached samplers.
    /// </summary>
    int Count { get; }

    /// <summary>
    /// Gets or creates a sampler resource from the given description.
    /// </summary>
    /// <param name="desc">The sampler state description.</param>
    /// <returns>
    /// A <see cref="SamplerRef"/> wrapping the sampler resource, either from cache or newly created.
    /// The repository is the sole owner of the underlying <see cref="SamplerResource"/>; callers must
    /// not call <c>AddReference</c> or <c>Dispose</c> on it directly.
    /// </returns>
    /// <exception cref="InvalidOperationException">Thrown if sampler creation fails.</exception>
    /// <exception cref="ObjectDisposedException">Thrown if the repository or context has been disposed.</exception>
    SamplerRef GetOrCreate(SamplerStateDesc desc);

    /// <summary>
    /// Removes and disposes the sampler entry associated with the given cache key.
    /// </summary>
    /// <param name="key">The cache key of the sampler to remove.</param>
    /// <returns>
    /// <c>true</c> if the entry was found and removed; <c>false</c> if the key did not exist in the cache.
    /// </returns>
    /// <remarks>
    /// After this method returns <c>true</c>, any <see cref="SamplerRef"/> instances previously
    /// returned for this key will return an invalid handle on their next <see cref="SamplerRef.GetHandle"/> call.
    /// </remarks>
    bool Remove(string key);

    /// <summary>
    /// Attempts to retrieve a cached sampler entry.
    /// </summary>
    /// <param name="cacheKey">The cache key generated by <see cref="SamplerRepository.GenerateCacheKey"/>.</param>
    /// <param name="entry">
    /// The cached sampler entry if found. Use <see cref="SamplerModuleCacheEntry.Ref"/> to obtain the
    /// <see cref="SamplerRef"/> that holds the live sampler resource.
    /// </param>
    /// <returns><c>true</c> if the sampler was found in cache; otherwise, <c>false</c>.</returns>
    bool TryGet(string cacheKey, out SamplerModuleCacheEntry? entry);

    /// <summary>
    /// Clears all cached samplers and disposes of them.
    /// </summary>
    void Clear();

    /// <summary>
    /// Removes and disposes expired sampler entries.
    /// </summary>
    /// <returns>The number of entries removed.</returns>
    int CleanupExpired();

    /// <summary>
    /// Gets cache statistics for monitoring and debugging.
    /// </summary>
    /// <returns>Statistics about the sampler repository cache.</returns>
    RepositoryStatistics GetStatistics();
}
