using HelixToolkit.Nex.Graphics;
// Import global types from HelixToolkit.Nex.Graphics
using size_t = uint;

namespace HelixToolkit.Nex.Repository;

/// <summary>
/// Interface for a thread-safe repository that caches compiled SPIR-V shader modules.
/// </summary>
/// <remarks>
/// This interface provides access to shader module caching functionality, enabling:
/// <list type="bullet">
/// <item><description>Automatic deduplication of shader modules</description></item>
/// <item><description>LRU eviction policy for memory management</description></item>
/// <item><description>Cache statistics and monitoring</description></item>
/// <item><description>Thread-safe concurrent access</description></item>
/// </list>
/// </remarks>
public interface IShaderRepository : IDisposable
{
    /// <summary>
    /// Gets the number of cached shader modules.
    /// </summary>
    int Count { get; }

    /// <summary>
    /// Gets or creates a shader module from GLSL source.
    /// </summary>
    /// <param name="stage">The shader stage.</param>
    /// <param name="glslSource">The GLSL source code.</param>
    /// <param name="defines">Optional shader defines.</param>
    /// <param name="debugName">Optional debug name for the shader module.</param>
    /// <returns>The shader module resource, either from cache or newly created.</returns>
    /// <exception cref="InvalidOperationException">Thrown if shader module creation fails.</exception>
    /// <exception cref="ArgumentException">Thrown if <paramref name="glslSource"/> is null or empty.</exception>
    /// <exception cref="ObjectDisposedException">Thrown if the repository or context has been disposed.</exception>
    ShaderModuleResource GetOrCreateFromGlsl(
        ShaderStage stage,
        string glslSource,
        ShaderDefine[]? defines = null,
        string? debugName = null
    );

    /// <summary>
    /// Gets or creates a shader module from SPIR-V bytecode.
    /// </summary>
    /// <param name="stage">The shader stage.</param>
    /// <param name="spirvData">Pointer to SPIR-V bytecode.</param>
    /// <param name="spirvSize">Size of SPIR-V bytecode in bytes.</param>
    /// <param name="debugName">Optional debug name for the shader module.</param>
    /// <returns>The shader module resource, either from cache or newly created.</returns>
    /// <exception cref="InvalidOperationException">Thrown if shader module creation fails.</exception>
    /// <exception cref="ArgumentException">Thrown if SPIR-V data is invalid.</exception>
    /// <exception cref="ObjectDisposedException">Thrown if the repository or context has been disposed.</exception>
    ShaderModuleResource GetOrCreateFromSpirv(
        ShaderStage stage,
        nint spirvData,
        size_t spirvSize,
        string? debugName = null
    );

    /// <summary>
    /// Attempts to retrieve a cached shader module entry.
    /// </summary>
    /// <param name="cacheKey">The cache key generated by <see cref="ShaderRepository.GenerateCacheKey"/>.</param>
    /// <param name="entry">The cached shader module entry if found.</param>
    /// <returns><c>true</c> if the shader module was found in cache; otherwise, <c>false</c>.</returns>
    bool TryGet(string cacheKey, out ShaderModuleCacheEntry? entry);

    /// <summary>
    /// Clears all cached shader modules and disposes of them.
    /// </summary>
    void Clear();

    /// <summary>
    /// Removes and disposes expired shader module entries.
    /// </summary>
    /// <returns>The number of entries removed.</returns>
    int CleanupExpired();

    /// <summary>
    /// Gets cache statistics for monitoring and debugging.
    /// </summary>
    /// <returns>Statistics about the shader repository cache.</returns>
    RepositoryStatistics GetStatistics();
}
