global using System.Diagnostics;
global using System.Numerics;
global using HelixToolkit.Nex.DependencyInjection;
global using HelixToolkit.Nex.Geometries;
global using HelixToolkit.Nex.Graphics;
global using HelixToolkit.Nex.Material;
global using HelixToolkit.Nex.Maths;
global using HelixToolkit.Nex.Repository;
global using HelixToolkit.Nex.Shaders;
global using HelixToolkit.Nex.Trace;
global using Microsoft.Extensions.Logging;
global using BufferHandle = HelixToolkit.Nex.Handle<HelixToolkit.Nex.Graphics.Buffer>;
global using TextureHandle = HelixToolkit.Nex.Handle<HelixToolkit.Nex.Graphics.Texture>;
