global using System.Diagnostics;
global using System.Runtime.InteropServices;
global using Microsoft.Extensions.Logging;
global using int32_t = int;
global using int8 = sbyte;
global using int8_t = sbyte;
global using size_t = uint;
global using TextureFormatCapabilities = byte;
global using uint32_t = uint;
global using uint64_t = ulong;
global using uint8 = byte;
global using uint8_t = byte;
