using System.Collections.Generic;
using System.Text;

namespace HelixToolkit.Nex.CodeGen;

/// <summary>
/// Generates C# struct code from parsed GLSL structs.
/// </summary>
public class CSharpStructGenerator
{
    private static readonly Dictionary<string, string> TypeMapping = new()
    {
        // Scalar types
        ["float"] = "float",
        ["double"] = "double",
        ["int"] = "int",
        ["uint"] = "uint",
        ["bool"] = "bool",
        ["uint64_t"] = "ulong",
        ["int64_t"] = "long",
        ["uint64"] = "ulong",
        ["int64"] = "long",

        // Vector types (2D)
        ["vec2"] = "System.Numerics.Vector2",
        ["ivec2"] = "System.Numerics.Vector2",
        ["uvec2"] = "System.Numerics.Vector2",
        ["bvec2"] = "System.Numerics.Vector2",
        ["dvec2"] = "System.Numerics.Vector2",

        // Vector types (3D)
        ["vec3"] = "System.Numerics.Vector3",
        ["ivec3"] = "System.Numerics.Vector3",
        ["uvec3"] = "System.Numerics.Vector3",
        ["bvec3"] = "System.Numerics.Vector3",
        ["dvec3"] = "System.Numerics.Vector3",

        // Vector types (4D)
        ["vec4"] = "System.Numerics.Vector4",
        ["ivec4"] = "System.Numerics.Vector4",
        ["uvec4"] = "System.Numerics.Vector4",
        ["bvec4"] = "System.Numerics.Vector4",
        ["dvec4"] = "System.Numerics.Vector4",

        // Matrix types
        ["mat2"] = "System.Numerics.Matrix3x2",
        ["mat3"] = "System.Numerics.Matrix4x4", // Note: No direct 3x3 in System.Numerics
        ["mat4"] = "System.Numerics.Matrix4x4",
        ["mat2x2"] = "System.Numerics.Matrix3x2",
        ["mat3x3"] = "System.Numerics.Matrix4x4",
        ["mat4x4"] = "System.Numerics.Matrix4x4",
    };

    public string Generate(string fileName, List<GlslStruct> structs)
    {
        var sb = new StringBuilder();

        // File header
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// This file was generated from " + fileName + ".glsl");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Runtime.InteropServices;");
        sb.AppendLine();
        sb.AppendLine("namespace HelixToolkit.Nex.Shaders;");
        sb.AppendLine();

        // Generate each struct
        foreach (var glslStruct in structs)
        {
            GenerateStruct(sb, glslStruct);
            sb.AppendLine();
        }

        return sb.ToString();
    }

    private void GenerateStruct(StringBuilder sb, GlslStruct glslStruct)
    {
        // XML documentation
        sb.AppendLine($"/// <summary>");
        sb.AppendLine($"/// C# representation of the GLSL struct '{glslStruct.Name}'.");
        sb.AppendLine($"/// </summary>");

        // StructLayout attribute for proper memory alignment
        sb.AppendLine("[StructLayout(LayoutKind.Sequential, Pack = 16)]");
        sb.AppendLine($"public struct {glslStruct.Name}");
        sb.AppendLine("{");

        // Generate SizeInBytes constant
        sb.AppendLine($"    /// <summary>");
        sb.AppendLine(
            $"    /// The size of the <see cref=\"{glslStruct.Name}\"/> struct, in bytes."
        );
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine(
            $"    public static readonly unsafe uint SizeInBytes = (uint)sizeof({glslStruct.Name});"
        );
        sb.AppendLine();

        // Generate fields
        foreach (var field in glslStruct.Fields)
        {
            GenerateField(sb, field);
        }

        sb.AppendLine("}");
    }

    private void GenerateField(StringBuilder sb, GlslField field)
    {
        var csharpType = MapGlslTypeToCSharp(field.GlslType);

        // Add comment if exists
        if (!string.IsNullOrEmpty(field.Comment))
        {
            sb.AppendLine($"    /// <summary>{field.Comment}</summary>");
        }

        // Generate field
        if (field.IsArray)
        {
            // For arrays, we need to create fixed-size arrays or use array syntax
            // GLSL arrays need special handling for marshaling
            sb.AppendLine(
                $"    /// <remarks>GLSL array: {field.GlslType}[{field.ArraySize}]</remarks>"
            );

            // Use MarshalAs for array size
            sb.AppendLine(
                $"    [MarshalAs(UnmanagedType.ByValArray, SizeConst = {field.ArraySize})]"
            );
            sb.AppendLine($"    public {csharpType}[]? {FormatFieldName(field.Name)};");
        }
        else
        {
            sb.AppendLine($"    public {csharpType} {FormatFieldName(field.Name)};");
        }

        sb.AppendLine();
    }

    private string MapGlslTypeToCSharp(string glslType)
    {
        // Check if it's a known GLSL primitive type
        if (TypeMapping.TryGetValue(glslType, out var csharpType))
        {
            return csharpType;
        }

        // If not found, assume it's a user-defined struct type
        // (should already be defined in the same namespace)
        return glslType;
    }

    private string FormatFieldName(string fieldName)
    {
        // Convert camelCase to PascalCase for C# convention
        if (string.IsNullOrEmpty(fieldName))
            return fieldName;

        // If it starts with lowercase, capitalize it
        if (char.IsLower(fieldName[0]))
        {
            return char.ToUpperInvariant(fieldName[0]) + fieldName.Substring(1);
        }

        return fieldName;
    }
}
